/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import static frm.grafica1.lblg1;
import static frm.grafica1.lblg2;
import static frm.grafica1.lblg3;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author CECYT8
 */
public class grafica extends javax.swing.JFrame {

        JTable tabla;
    ResultSet rs;
        ImageIcon Imagen=new ImageIcon();
    ImageIcon jr=new ImageIcon();
    /**
     * Creates new form grafica
     */
    public grafica() throws SQLException {
        

        
        
        
             
            initComponents();
                    Imagen=new ImageIcon(getClass().getResource("/Imagenes/fondo1.jpg"));
        ImageIcon ImgScal=new ImageIcon(Imagen.getImage().getScaledInstance(lblFondo.getWidth(),lblFondo.getHeight(),Image.SCALE_DEFAULT));
        lblFondo.setIcon(ImgScal);
            lblg1.setVisible(false);
            lblg2.setVisible(false);
            lblg3.setVisible(false);
pnl1.setVisible(false);
   pnl2.setVisible(false);       
            setLocationRelativeTo(null);
           
              setIconImage(new ImageIcon(getClass().getResource("../Imagenes/icono1.jpg")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        lblg3 = new javax.swing.JLabel();
        lblg2 = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnl1 = new javax.swing.JPanel();
        btnFin = new javax.swing.JButton();
        lblg1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setText("¿Donde deseas visualizar los resultados?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jCheckBox1.setText("TABLA");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 22, -1, -1));

        jCheckBox2.setText("GRAFICA");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 22, -1, -1));
        getContentPane().add(lblg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 426, 53, 24));
        getContentPane().add(lblg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 426, 52, 14));

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        getContentPane().add(pnl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        pnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 480, 280));

        btnFin.setText("Finalizar");
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinActionPerformed(evt);
            }
        });
        getContentPane().add(btnFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 417, -1, -1));
        getContentPane().add(lblg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 426, 46, 14));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed

        pnl1.setVisible(true);
                    Seleccion JSeleccion = new Seleccion();
lblg1.setText(JSeleccion.lbl1.getText());
lblg2.setText(JSeleccion.lbl2.getText());
lblg3.setText(JSeleccion.lbl3.getText());

        String SQL="";
        String SQL1="";
        String SQL2="";
        String SQL3="";
        int Dato=0;
        int Dato1=0;
        int Dato2=0;


String cand1 = lblg1.getText();
String cand2 = lblg2.getText();
String cand3 = lblg3.getText();

        Conectar con = new Conectar();
         Connection cnn = con.getConnection();
         try{
         Statement st = cnn.createStatement();
         SQL = "select votos from voto where id = '"+cand1+"'";
          ResultSet rs = st.executeQuery(SQL);
         while(rs.next()){
             Dato = rs.getInt("votos");
             }
                  SQL1 = "select votos from voto where id = '"+cand2+"'";
          ResultSet rs1 = st.executeQuery(SQL1);
         while(rs1.next()){
             Dato1 = rs1.getInt("votos");
             }
                  SQL2 = "select votos from voto where id = '"+cand3+"'";
          ResultSet rs2 = st.executeQuery(SQL2);
         while(rs2.next()){
             Dato2 = rs2.getInt("votos");
             }
         } catch(SQLException ex){
             
         }
 
                DefaultCategoryDataset dataset = new DefaultCategoryDataset();
dataset.setValue(Dato, "'"+cand1+"'", "'"+cand1+"'");
dataset.setValue(Dato1, "'"+cand2+"'", "'"+cand2+"'");
dataset.setValue(Dato2, "'"+cand3+"'", "'"+cand3+"'");

JFreeChart chart = ChartFactory.createBarChart("VOTACIONES",
"CANDIDATOS", "VOTOS", dataset, PlotOrientation.VERTICAL,
false, true, false);

        ChartPanel panel = new ChartPanel(chart);        
        pnl1.setLayout(new java.awt.BorderLayout());
        pnl1.add(panel);   
        pnl1.validate();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       try {
           pnl2.setVisible(true);
            setResizable(false);
            DefaultTableModel dfm = new DefaultTableModel();

            tabla = this.jTable1;
            tabla.setModel(dfm);

            dfm.setColumnIdentifiers(new Object[]{"Candidato", "votos"});
      Conectar con = new Conectar();
         Connection cnn = con.getConnection();
            rs = con.Resultado();

            while (rs.next()) {
                dfm.addRow(new Object[]{rs.getString("id"), rs.getInt("votos")});
            }
        } catch (SQLException ex) {
            Logger.getLogger(grafica.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinActionPerformed
                Conectar con = new Conectar();
        Connection cnn = con.getConnection();
String cand1 = lblg1.getText();
String cand2 = lblg2.getText();
String cand3 = lblg3.getText();
            try {
                PreparedStatement del = cnn.prepareStatement(" delete from  voto where id='"+cand1+"'");
                PreparedStatement del2 = cnn.prepareStatement(" delete from  voto where id='"+cand2+"'");
                PreparedStatement del3 = cnn.prepareStatement(" delete from  voto where id='"+cand3+"'");
                del.executeUpdate();
                del2.executeUpdate();
                del3.executeUpdate();
       

            } catch (SQLException ex) {

            }
            System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new grafica().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(grafica.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFin;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFondo;
    public static javax.swing.JLabel lblg1;
    public static javax.swing.JLabel lblg2;
    public static javax.swing.JLabel lblg3;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    // End of variables declaration//GEN-END:variables
}
