/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;
import frm.Cerrar;
import frm.Registro;
import frm.grafica;
import frm.votantes;
import static frm.Registro.txtRcontra;
import static frm.Registro.txtRnombre;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CECYT8
 */
public class Seleccion extends javax.swing.JFrame {
        public static String cand1="" ;
        public static String cand2="" ;
        public static String cand3="" ;
        public static String cand ="";
        public static String adm="";
        public static String numero="";
    /**
     * Creates new form Seleccion
     */

    
    public Seleccion() {
        initComponents();
        lbl4.setVisible(false);
        lblnum.setVisible(false);
        setLocationRelativeTo(null);
        setResizable(false);
         setIconImage(new ImageIcon(getClass().getResource("../Imagenes/icono1.jpg")).getImage());


            lbl1.setText(cand1);
            lbl2.setText(cand2);
            lbl3.setText(cand3);
            lbl4.setText(adm);
        
        if (lbl1.getText().equals("") && lbl2.getText().equals("") &&  lbl3.getText().equals("") ){
       
            lbl1.setText("candidato 1");
            lbl2.setText("candidato 2");
            lbl3.setText("candidato 3");
    }
        else {
            lbl1.setText(cand1);
            lbl2.setText(cand2);
            lbl3.setText(cand3);
        }
        if(cand.equals("2")){
            pnl3.setVisible(false);
        }else
            pnl3.setVisible(true);
        
        if(adm.equals("1")){
            btnEmpezar.setVisible(false);
            btnAgregar.setVisible(false);
        }else{
                        btnEmpezar.setVisible(true);
            btnAgregar.setVisible(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl3 = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        btnVotar1 = new javax.swing.JButton();
        btnVotar = new javax.swing.JButton();
        btnVotar2 = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEmpezar = new javax.swing.JButton();
        lbl4 = new javax.swing.JLabel();
        lblnum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("CANDIDATOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        pnl3.setBackground(new java.awt.Color(153, 0, 51));
        pnl3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(204, 255, 255));
        pnl3.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        btnVotar1.setText("Votar");
        btnVotar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotar1ActionPerformed(evt);
            }
        });
        pnl3.add(btnVotar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel1.add(pnl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 110, 70));

        btnVotar.setText("Votar");
        btnVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVotar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        btnVotar2.setText("Votar");
        btnVotar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVotar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl1.setForeground(new java.awt.Color(204, 255, 255));
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 100, 17));

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl2.setForeground(new java.awt.Color(204, 255, 255));
        jPanel1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 90, 18));

        btnAgregar.setText("agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnEmpezar.setText("Empezar");
        btnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));
        jPanel1.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 20, 10));
        jPanel1.add(lblnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 50, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotarActionPerformed
 
        Cerrar JC = new Cerrar();
        JC.setVisible(true);
        this.setVisible(false);
        
         cand1 = lbl1.getText();
         cand2 = lbl2.getText();
         cand3 = lbl3.getText();
         adm = lbl4.getText();

        Conectar con = new Conectar();
        Connection cnn = con.getConnection();

        try {
            PreparedStatement pps = cnn.prepareStatement("update voto set votos=votos+1 where id='"+cand1+"' ");
            pps.executeUpdate();

        } catch (SQLException ex) {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVotarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed


        
        if(lbl1.getText().equals("candidato 1") || lbl2.getText().equals("candidato 2") || lbl3.getText().equals("candidato 3")){
            
                     cand = JOptionPane.showInputDialog("¿Son 2 o 3 candidatos?");
       switch(cand){
           case "2":
               if(lbl1.getText().equals("candidato 1") && lbl2.getText().equals("candidato 2") ){
        try {
            cand1=(JOptionPane.showInputDialog("Primer candidato"));
            cand2 =(JOptionPane.showInputDialog("Segundo candidato"));
            adm= "1";
            pnl3.setVisible(false);
            
            
            lbl1.setText(cand1);
            lbl2.setText(cand2);
            lbl3.setText(cand3);
            lbl4.setText(adm);
            
            grafica Jgrafica = new grafica();
            Jgrafica.lblg1.setText(cand1);
            Jgrafica.lblg2.setText(cand2);
            Jgrafica.lblg3.setText(cand3);
            
            
            Conectar con = new Conectar();
            Connection cnn = con.getConnection();
            String cand1 = lbl1.getText();
            String cand2 = lbl2.getText();
            String cand3 = lbl3.getText();
            
            try {
                PreparedStatement pst = cnn.prepareStatement("insert into voto (id,votos) values (?,?)");
                pst.setString(1,cand1);
                pst.setString(2, "0");
                pst.executeUpdate();
                // TODO add your handling code here:
                
            } catch (SQLException ex) {
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"ERROR EN EL REGRISTRO");
            }
            try {
                PreparedStatement pst1 = cnn.prepareStatement("insert into voto (id,votos) values (?,?)");
                pst1.setString(1,cand2);
                pst1.setString(2, "0");
                pst1.executeUpdate();
                // TODO add your handling code here:
                
            } catch (SQLException ex) {
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"ERROR EN EL REGRISTRO");
            }
            try {
                PreparedStatement pst2 = cnn.prepareStatement("insert into voto (id,votos) values (?,?)");
                pst2.setString(1,cand3);
                pst2.setString(2, "0");
                pst2.executeUpdate();
                // TODO add your handling code here:
                
            } catch (SQLException ex) {
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"ERROR EN EL REGRISTRO");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Seleccion.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
        }else{

        }
               
               break;
           case "3":
               if(lbl1.getText().equals("candidato 1") && lbl2.getText().equals("candidato 2") ){
        try {
            cand1=(JOptionPane.showInputDialog("Primer candidato"));
            cand2 =(JOptionPane.showInputDialog("Segundo candidato"));
            cand3 =(JOptionPane.showInputDialog("Tercer candidato"));
            adm= "1";
            pnl3.setVisible(true);
            
            
            lbl1.setText(cand1);
            lbl2.setText(cand2);
            lbl3.setText(cand3);
            lbl4.setText(adm);
            
            grafica Jgrafica = new grafica();
            Jgrafica.lblg1.setText(cand1);
            Jgrafica.lblg2.setText(cand2);
            Jgrafica.lblg3.setText(cand3);
            
            
            Conectar con = new Conectar();
            Connection cnn = con.getConnection();
            String cand1 = lbl1.getText();
            String cand2 = lbl2.getText();
            String cand3 = lbl3.getText();
            
            try {
                PreparedStatement pst = cnn.prepareStatement("insert into voto (id,votos) values (?,?)");
                pst.setString(1,cand1);
                pst.setString(2, "0");
                pst.executeUpdate();
                // TODO add your handling code here:
                
            } catch (SQLException ex) {
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"ERROR EN EL REGRISTRO");
            }
            try {
                PreparedStatement pst1 = cnn.prepareStatement("insert into voto (id,votos) values (?,?)");
                pst1.setString(1,cand2);
                pst1.setString(2, "0");
                pst1.executeUpdate();
                // TODO add your handling code here:
                
            } catch (SQLException ex) {
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"ERROR EN EL REGRISTRO");
            }
            try {
                PreparedStatement pst2 = cnn.prepareStatement("insert into voto (id,votos) values (?,?)");
                pst2.setString(1,cand3);
                pst2.setString(2, "0");
                pst2.executeUpdate();
                // TODO add your handling code here:
                
            } catch (SQLException ex) {
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"ERROR EN EL REGRISTRO");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Seleccion.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
        }else{

        }
               
               break;

        }}else{
            
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarActionPerformed

        votantes Jvotantes = new votantes();
Jvotantes.setVisible(true);
this.setVisible(false);   
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmpezarActionPerformed

    private void btnVotar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotar2ActionPerformed

                Cerrar JC = new Cerrar();
        JC.setVisible(true);
        this.setVisible(false);
         cand1 = lbl1.getText();
         cand2 = lbl2.getText();
         cand3 = lbl3.getText();
         adm = lbl4.getText();

        Conectar con = new Conectar();
        Connection cnn = con.getConnection();

        try {
            PreparedStatement pps = cnn.prepareStatement("update voto set votos=votos+1 where id='"+cand2+"' ");
            pps.executeUpdate();

        } catch (SQLException ex) {

        }       
        
    }//GEN-LAST:event_btnVotar2ActionPerformed

    private void btnVotar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotar1ActionPerformed
        Cerrar JC = new Cerrar();
        JC.setVisible(true);
        this.setVisible(false);
         cand1 = lbl1.getText();
         cand2 = lbl2.getText();
         cand3 = lbl3.getText();
         adm = lbl4.getText();

        Conectar con = new Conectar();
        Connection cnn = con.getConnection();

        try {
            PreparedStatement pps = cnn.prepareStatement("update voto set votos=votos+1 where id='"+cand3+"' ");
            pps.executeUpdate();

        } catch (SQLException ex) {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVotar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JButton btnVotar;
    private javax.swing.JButton btnVotar1;
    private javax.swing.JButton btnVotar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbl1;
    public javax.swing.JLabel lbl2;
    public javax.swing.JLabel lbl3;
    public static javax.swing.JLabel lbl4;
    public static javax.swing.JLabel lblnum;
    public static javax.swing.JPanel pnl3;
    // End of variables declaration//GEN-END:variables
}
